yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("posts/<int:post_id>/delete/", views.post_delete, name="post_delete"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path(
        "comment/<int:comment_id>/",
        views.delete_comment,
        name="delete_comment",
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
    path("like/<int:post_id>/", views.post_like, name="likes"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
]
handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts"
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name="posts",
        on_delete=models.SET_NULL,
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    likes = models.ManyToManyField(User, related_name="likes")

    def likes_count(self):
        return self.likes.count()

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name="comments",
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name="comments",
        on_delete=models.CASCADE,
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_following"
            )
        ]

    def __str__(self):
        return self.author

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )
        labels = {
            "text": _("Текст поста"),
            "group": _("Группа"),
        }
        help_texts = {
            "text": _("Текст нового поста"),
            "group": _("Группа, к которой будет относиться пост"),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        labels = {"text": _("Текст комментария")}
        help_texts = {
            "text": _("Текст нового комментария"),
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import paginator_func


@cache_page(5, key_prefix="index_page")
def index(request):
    template = "posts/index.html"
    post_list = Post.objects.all()
    context = {"page_obj": paginator_func(post_list, request)}
    return render(request, template, context)


def group_posts(request, slug):
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    group_post_list = group.posts.all()
    context = {
        "group": group,
        "page_obj": paginator_func(group_post_list, request),
    }
    return render(request, template, context)


def profile(request, username):
    template = "posts/profile.html"
    author = get_object_or_404(User, username=username)
    author_post = author.posts.all()
    posts_count = author_post.count()
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {
        "page_obj": paginator_func(author_post, request),
        "author": author,
        "posts_count": posts_count,
        "following": following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = "posts/post_detail.html"
    post = get_object_or_404(Post, pk=post_id)
    posts_count = post.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = post.comments.all()

    liked = False

    if post.likes.filter(id=request.user.id).exists():
        liked = True

    context = {
        "post": post,
        "posts_count": posts_count,
        "form": form,
        "comments": comments,
        "likes_count": post.likes_count(),
        "post_is_liked": liked,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = "posts/create_post.html"
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=post.author)
    context = {
        "form": form,
        "is_edit": False,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = "posts/create_post.html"
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None, files=request.FILES or None, instance=post
    )
    if request.user != post.author:
        return redirect("posts:post_detail", post.pk)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post.pk)
    context = {
        "form": form,
        "is_edit": True,
    }
    return render(request, template, context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user == post.author:
        post.delete()
    return redirect("posts:profile", username=post.author)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post_comment_id = comment.post_id
    if request.user.username == comment.author.username:
        comment.delete()
    return redirect("posts:post_detail", post_comment_id)


@login_required
def follow_index(request):
    template = "posts/follow.html"
    posts = Post.objects.filter(author__following__user=request.user)
    context = {"page_obj": paginator_func(posts, request)}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    follower = request.user
    following = get_object_or_404(User, username=username)
    if follower != following:
        Follow.objects.get_or_create(user=follower, author=following)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    follower = request.user
    following = get_object_or_404(User, username=username)
    followed = Follow.objects.filter(user=follower, author=following)
    if followed.exists():
        followed.delete()
    return redirect("posts:profile", username=username)


@login_required
def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return redirect("posts:post_detail", post_id=post_id)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}            
        </div>
        <div class="card-body">   
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}     
          
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
          
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  <article>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
      <br>
      {% if post.author %}
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </article>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}

{% block title %} 
  {{ group }} 
{% endblock %} 

{% block content %}
  <h1>{{ group }}</h1>
  <p>
    {{ group.description }}
  </p>
  <article>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>  
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}    
      <p>{{ post.text }}</p>  
      {% if post.author %}
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}  
    {% include 'posts/includes/paginator.html' %}  
  </article>
{% endblock  %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  <article>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x450" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a class="btn btn-primary" href="{% url 'posts:group_list' post.group.slug %}">
          Все записи группы
        </a>
      {% endif %}
      <br> <br>
      {% if post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_detail' post.id %}">
          Подробная информация
        </a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </article>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% load thumbnail %}

{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }} <br>
            <a href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ posts_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          Редактировать запись
        </a>
      {% endif %}
      {% if post.author == request.user %}
        <a class="btn btn-secondary" href="{% url 'posts:post_delete' post.pk %}">
          Удалить запись
        </a>
      {% endif %}
      <br>
      <br>
      {% if user.is_authenticated %}
        <form action="{% url 'posts:likes' post.pk%}" method="POST">
          {% csrf_token %}
          {% if post_is_liked %}
            <button type="submit" name="post_id" value="{{post.pk}}" class="btn btn-info">
              Не нравится
            </button>
          {% else %}
            <button type="submit" name="post_id" value="{{post.pk}}" class="btn btn-info">
              Нравится
            </button>
          {% endif %}
        </form>
      {% else %}
        <a class="btn btn-outline-info" href="{% url 'login' %}?next={{request.path}}">
          Log in to like this article!
        </a>
        <br>
      {% endif %}
      <strong class="text-secondary">{{ likes_count }} Like{{ likes_count|pluralize }}</strong>
      {% include "posts/includes/post_comment.html" %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% load thumbnail %}

{% block title %} 
  Профайл пользователя {{ author.username }}
{% endblock %} 

{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.username }} </h1>
    <h3>Всего постов: {{ posts_count }} </h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
  </div>
  <article>
    {% for post in page_obj %}
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if post.author %}
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
      {% endif %}
      <br>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  </article>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}